### PR TITLE
Update NPM to version 6.5.0

### PR DESCRIPTION
**Pull request by miketypeguy**
We need NPM upgraded to a newer version to make use of some NPM features in regards to nodejs projects.  Determined that you must upgrade node version before you update npm or you get an issue as seen in various internet posts (e.g. https://stackoverflow.com/questions/50316693/npm-update-broke-npm).   This has build successfully now.

### CODE REVIEW

**Review by haggaret — APPROVED** [review]
Great Success!

**Comment by dnorth98** [comment]
Outrageous!

(not sure why but I was notified for this :) )

**Comment by miketypeguy** [comment]
> Outrageous!
> 
> (not sure why but I was notified for this :) )

Apparently you are a contributor on this repo. We can remove you.  You can also click "unsubscribe" ;)

**Comment by dnorth98** [comment]
Gone but not forgotten..... :)

**Comment by miketypeguy** [comment]
> Gone but not forgotten..... :)

As an update because you're a contributor you'll always be notified on this until you unsubscribe from notifications as this is a public repo, or so I'm seeing.  You're not actually associated in any other way and you were not requested to review.

**Pull request merged**
